name: Tag the current Mavkit release


on:
  push:
    branches:
      - 'master'

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Force push tag of the current Mavkit release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: make release
        run: make release

      - uses: rhosys/github-action-rebuild-pull-requests@v1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
